name: Linux CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Install FPC
        run: |
          sudo apt-get update
          sudo apt-get install -y lazarus
      - uses: actions/checkout@v2
      - name: Run tests
        run: lazbuild bench/benchmark.lpr
