name: Windows CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Install FPC
        run: |
          choco install lazarus
      - uses: actions/checkout@v2
      - name: Compile tests
        run: lazbuild bench/benchmark.lpr
      - name: Run tests
        run: bench\benchmark.exe
